### ISSUE TITLE
dynamic library image not found in Xcode 8.3.3

### ISSUE THREAD

**Issue by appsird** [insidegui/NoteTaker#1]
Thanks for the example.

I successfully downloaded, installed Carthage, built the libraries, then compiled all targets without error after adding frameworks. no errors.

Though when running the macOS target I receive the following error. Yet I see the library exists. Any ideas?

dyld: Library not loaded: @rpath/RxBlocking.framework/Versions/A/RxBlocking
  Referenced from: /Users/brianx/Library/Developer/Xcode/DerivedData/NoteTaker-cpbpovvmztmzarelwffrafpjvcsr/Build/Products/Debug/NoteTaker.app/Contents/MacOS/NoteTaker
  Reason: image not found
(lldb)

**Comment by appsird** [comment]
disregard, I determined I required to add RxBlocking.framework to Embed Frameworks for both iOS and macOS targets as per image below. I was then able to run.

![x](https://user-images.githubusercontent.com/8471833/30253453-2d460dd4-963a-11e7-87af-5646220d2473.png)

**Comment by insidegui** [comment]
Great! Have fun :)
